apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o5i5eb97v-go 
  janus-idp.io/tekton: o5i5eb97v-go
  backstage.io/kubernetes-id: o5i5eb97v-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o5i5eb97v-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  